services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always


 
docker run -it \
  -e POSTGRES_USER="root" \ # environmental configurations
  -e POSTGRES_PASSWORD="root" \
  -e POSTGRES_DB="ny_taxi" \   # name of the database
  -v /workspaces/data-engineering/ny_taxi_postgres_data:/var/lib/postgresql/data \  # mount a volume: possibility to map a folder we have on the host machine to our container
  -p 5432:5432 \ # specify the port, map a port on our host machine to a port of the conatiner
  postgres:13











